name: iitj_rent_sell
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  flutter_native_splash: ^2.3.9
  animated_text_kit: ^4.2.2
  email_validator: ^2.1.17
  flutter_neumorphic: ^3.2.0


  google_fonts: ^4.0.3
  flutter_signin_button: ^2.0.0
  pinput: ^2.2.31
  line_awesome_flutter: ^2.0.0
  firebase_core: ^2.24.2
  firebase_auth: ^4.2.10
  get: ^4.6.5
  cloud_firestore: ^4.4.4
  firebase_admin: ^0.2.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
     - assets/images/
  #   - images/a_dot_ham.jpeg


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
